[package]
name = "ip2bin"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ip_network = "0.4"
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
